<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Asyn / Await from javascript.info 2</title>
</head>

<body>
  <!-- https://javascript.info/async-await exersize "Rewrite "rethrow" with async/await" -->

  <script>

    class HttpError extends Error {
      constructor(response) {
        super(`${response.status} for ${response.url}`);
        this.name = 'HttpError';
        this.response = response;
      }
    }

    async function loadJson(url) {
      const response = await fetch(url);
      if (response.status == 200) {
        return await response.json();
      }
      throw new HttpError(response);
    }

    // Ask for a user name until github returns a valid user
    async function demoGithubUser() {
      let name = prompt("Enter a name?", "iliakan");
      let toContinue = true;
      while (toContinue) {
        try {
          let response = await loadJson(`https://api.github.com/users/${name}`);
          alert(`Full name: ${response.name}.`);
          toContinue = false;
        } catch (err) {
          if (err instanceof HttpError && err.response.status == 404) {
            alert("No such user, please reenter.");
          } else {
            throw err;
          }
        }
      }
    }

    demoGithubUser();
  </script>
</body>

</html>